services:
  - type: web
    name: 7k-ocr-service
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT ocr_service:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    nativeEnvironments:
      - name: tesseract
